### ISSUE TITLE
Дополнение инструкции по установке 2

### ISSUE THREAD

**Issue by valsha** [BuyOwnEx/BOEClient#30]
Не указано какая версия nodejs должна быть установлена и вообще что надо установить nodejs

после запуска  

1. sudo php artisan serve --host my_ext_ip --port 8081
`PHP Fatal error:  Uncaught Exception: The Mix manifest does not exist. in /home/boeclient/vendor/laravel/framework/src/Illuminate/Foundation/Mix.php:46`

после установки nodejs v14.17.1  и запуска sudo npm run production

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'production' ]
2 info using npm@6.14.13
3 info using node@v14.17.1
4 verbose run-script [ 'preproduction', 'production', 'postproduction' ]
5 info lifecycle @lux/laravel-starter@1.5.1~preproduction: @lux/laravel-starter@1.5.1
6 info lifecycle @lux/laravel-starter@1.5.1~production: @lux/laravel-starter@1.5.1
7 verbose lifecycle @lux/laravel-starter@1.5.1~production: unsafe-perm in lifecycle true
8 verbose lifecycle @lux/laravel-starter@1.5.1~production: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/boeclient/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle @lux/laravel-starter@1.5.1~production: CWD: /home/boeclient
10 silly lifecycle @lux/laravel-starter@1.5.1~production: Args: [ '-c', 'mix --production' ]
11 silly lifecycle @lux/laravel-starter@1.5.1~production: Returned: code: 2  signal: null
12 info lifecycle @lux/laravel-starter@1.5.1~production: Failed to exec production script
13 verbose stack Error: @lux/laravel-starter@1.5.1 production: `mix --production`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:375:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:375:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid @lux/laravel-starter@1.5.1
15 verbose cwd /home/boeclient
16 verbose Linux 5.4.0-56-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "production"
18 verbose node v14.17.1
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 2
22 error @lux/laravel-starter@1.5.1 production: `mix --production`
22 error Exit status 2
23 error Failed at the @lux/laravel-starter@1.5.1 production script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by valsha** [comment]
если использовать `sudo npm run dev` то вроде все ок

**Comment by BuyOwnEx** [comment]
Поскольку сборка осуществляется посредством laravel-mix, то следует руководствоваться их рекомендациями по версии nodejs, а у них прописано "node": ">=12.14.0"
У нас на 12-ой и на 14-ой версии node сборка прошла успешна как dev так и prod
Обновили все пакеты по front-end, попробуйте последнюю версию
